# Generated by Django 3.2.13 on 2022-04-30 16:26

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0002_alter_empresa_logoempresa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacante',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ClienteFinal', models.CharField(max_length=200)),
                ('CargoSolicitado', models.CharField(max_length=200)),
                ('cantidad', models.PositiveIntegerField()),
                ('Genero', models.CharField(choices=[('Ambos', 'Ambos'), ('Hombre', 'Hombre'), ('Mujer', 'Mujer')], max_length=200, null=True)),
                ('EdadMinima', models.PositiveIntegerField(default=18, validators=[django.core.validators.MinValueValidator(16), django.core.validators.MaxValueValidator(60)])),
                ('EdadMaxima', models.PositiveIntegerField(default=45, validators=[django.core.validators.MinValueValidator(18), django.core.validators.MaxValueValidator(60)])),
                ('Educacion', models.CharField(choices=[('*', '*'), ('Primaria', 'Primaria'), ('Bachiller', 'Bachiller'), ('Técnica Laboral', 'Técnica Laboral'), ('Técnica Profesional', 'Técnica Profesional'), ('Tecnológica', 'Tecnológica'), ('Universitaria', 'Universitaria')], default='Bachiller', max_length=50)),
                ('AreaFormacion', models.CharField(max_length=200)),
                ('Especializacion', models.CharField(choices=[('NO', 'NO'), ('Especialización', 'Especialización'), ('Maestría', 'Maestría'), ('Doctorado', 'Doctorado')], default='NO', max_length=50)),
                ('Certificados', models.CharField(default='NO', max_length=200)),
                ('Pase', models.CharField(default='NO', max_length=200)),
                ('MesesExperiencia', models.PositiveIntegerField()),
                ('ConocimientoEspecifico', models.TextField()),
                ('FuncionesCargo', models.TextField(blank=True, default='Encargado de ', null=True)),
                ('Horario', models.CharField(default='Lunes-Sábado', max_length=200)),
                ('Presencialidad', models.CharField(choices=[('Presencial', 'Presencial'), ('Virtual', 'Virtual'), ('Presencial y Virtual', 'Presencial y Virtual')], default='Presencial', max_length=50)),
                ('SitioLabor', models.CharField(max_length=200)),
                ('Salario', models.DecimalField(decimal_places=0, max_digits=9)),
                ('Bonos', models.CharField(max_length=200)),
                ('SalarioEmocional', models.CharField(max_length=200)),
                ('TipoContrato', models.CharField(choices=[('Prestacion Servicios', 'Prestacion Servicios'), ('Obra o Labor', 'Obra o Labor'), ('Termino Fijo', 'Termino Fijo'), ('Indefinido', 'Indefinido')], default='Obra o Labor', max_length=50)),
                ('NotaEspecial', models.TextField()),
                ('Entrevista', models.CharField(choices=[('Presencial', 'Presencial'), ('Virtual', 'Virtual'), ('Presencial y Virtual', 'Presencial y Virtual')], default='Presencial', max_length=50)),
                ('direccionEntrevista', models.CharField(max_length=200)),
                ('FechaInicio', models.DateField()),
                ('FechaFin', models.DateField()),
                ('EstadoDDR', models.CharField(choices=[('Abierta', 'Abierta'), ('Cerrada', 'Cerrada'), ('Suspendida', 'Suspendida')], default='Abierta', max_length=50, verbose_name='Estado')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('Ciudad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clientes.ciudades')),
                ('Cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clientes.empresa')),
                ('Depto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clientes.departamentos')),
                ('Sector', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clientes.sectoreconomico')),
                ('contacto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clientes.contactos')),
            ],
            options={
                'ordering': ('Cliente',),
            },
        ),
    ]
