# Generated by Django 3.2.13 on 2022-05-03 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectovacantes', '0002_archivovacante_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivovacante',
            name='categoria',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='vacante',
            name='FechaFin',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='vacante',
            name='FechaInicio',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='vacante',
            name='MesesExperiencia',
            field=models.PositiveIntegerField(default='1'),
        ),
        migrations.AlterField(
            model_name='vacante',
            name='Salario',
            field=models.DecimalField(decimal_places=0, default='0', max_digits=9),
        ),
        migrations.AlterField(
            model_name='vacante',
            name='cantidad',
            field=models.PositiveIntegerField(default='1'),
        ),
    ]
