# Generated by Django 3.2.13 on 2022-05-04 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectovacantes', '0004_auto_20220503_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivovacante',
            name='vacante',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
