# Generated by Django 3.2.13 on 2022-05-06 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectovacantes', '0005_alter_archivovacante_vacante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivovacante',
            name='archivo',
            field=models.FileField(upload_to='imagenes/documents/'),
        ),
    ]
