# Generated by Django 3.2.13 on 2022-05-06 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectovacantes', '0006_alter_archivovacante_archivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivovacante',
            name='formularios',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
