# Generated by Django 3.2.13 on 2022-05-06 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectovacantes', '0007_archivovacante_formularios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivovacante',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='imagenes/documents/'),
        ),
    ]
