# Generated by Django 3.2.13 on 2022-05-07 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyectovacantes', '0008_alter_archivovacante_archivo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='archivovacante',
            options={'ordering': ('id',)},
        ),
    ]
