# Generated by Django 3.2.13 on 2022-05-12 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectovacantes', '0009_alter_archivovacante_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivovacante',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='imagenes/'),
        ),
    ]
