# Generated by Django 3.2.13 on 2022-04-23 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ciudades',
            fields=[
                ('idCiudad', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Ciudad', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='departamentos',
            fields=[
                ('idDepto', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Departamento', models.CharField(max_length=50, null=True)),
            ],
            options={
                'ordering': ('Departamento',),
            },
        ),
        migrations.CreateModel(
            name='paises',
            fields=[
                ('IdPais', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('pais', models.CharField(max_length=50, null=True)),
                ('Simbol', models.CharField(max_length=50, null=True)),
            ],
            options={
                'ordering': ('pais',),
            },
        ),
        migrations.CreateModel(
            name='SectorEconomico',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Sector', models.CharField(max_length=200, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'SectorEconomico',
                'ordering': ('Sector',),
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nit', models.CharField(max_length=200)),
                ('dv', models.CharField(max_length=10)),
                ('RazonSocial', models.CharField(max_length=200, null=True)),
                ('Direccion', models.CharField(max_length=200, null=True)),
                ('telefonos', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('logoEmpresa', models.ImageField(blank=True, null=True, upload_to='imagenes/', verbose_name='logo')),
                ('Actividad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clientes.sectoreconomico', verbose_name='Actividad Economica')),
                ('Ciudad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clientes.ciudades')),
                ('Depto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clientes.departamentos')),
                ('Pais', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clientes.paises')),
            ],
            options={
                'verbose_name_plural': 'Empresa',
                'ordering': ('RazonSocial',),
            },
        ),
        migrations.AddField(
            model_name='departamentos',
            name='IdPais',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clientes.paises'),
        ),
        migrations.CreateModel(
            name='Contactos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=200, null=True)),
                ('Cargo', models.CharField(max_length=200, null=True)),
                ('celular', models.CharField(max_length=200, null=True)),
                ('Correo', models.EmailField(max_length=254)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('Ciudad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clientes.ciudades')),
                ('Depto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clientes.departamentos')),
                ('Empresa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clientes.empresa')),
                ('Pais', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clientes.paises')),
            ],
            options={
                'verbose_name_plural': 'Directorio',
                'ordering': ('Empresa', 'Nombre'),
            },
        ),
        migrations.AddField(
            model_name='ciudades',
            name='IdPais',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clientes.paises'),
        ),
        migrations.AddField(
            model_name='ciudades',
            name='idDepto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clientes.departamentos'),
        ),
    ]
