# Generated by Django 3.2.13 on 2022-04-30 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='logoEmpresa',
            field=models.ImageField(blank=True, default='imagenes/3.png', null=True, upload_to='imagenes/', verbose_name='logo'),
        ),
    ]
