# Generated by Django 3.2.13 on 2022-05-12 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_alter_empresa_logoempresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='web',
            field=models.CharField(default='www', max_length=200),
        ),
    ]
